### ISSUE TITLE
WP Rocket: WP_CACHE constant

### ISSUE THREAD

**Issue by brettsmason** [eighteen73/orbit#1]
Look at a way to handle WP Rockets in built way of adding `WP_CACHE` to` web/wp-config.php`.

The easiest way is with a filter:

```
add_filter( 'rocket_set_wp_cache_constant', '__return_false' );
```

To decide where this lives - in Nebula or Orbit.

**Comment by edjeavons** [comment]
My gut says it should go in Orbit because that's where we can be a little more opinionated about other plugins that may be installed on the website. What do you think, @brettsmason?

**Comment by brettsmason** [comment]
Yes agreed, it should live in Orbit. We want to avoid anything being defined within wp-config.php

**Comment by edjeavons** [comment]
In the end I wasn't sure how to achieve it cleanly outside of Nebula because the `.gitignore` entries have to be in that repo anyway, plus the config still needs to be set before other plugins are loaded.

I did some testing and setting `Config::define( 'WP_CACHE', true );` ourselves in [config/application.php](https://github.com/eighteen73/nebula/commit/4ff9d3b0260309261ab42de2d8b2cdef3130339a#diff-53ea5a45a4b413ca49c7fac3f022e1dcbc2c203dcab4a1e7a34d1a8d65b26977) also has the side affect of preventing WP Rocket (and another caching plugin I tested) from rewriting that themselves, so perhaps that's the way to go. That means we don't need to apply their filter at all.

**Comment by edjeavons** [comment]
The filter mentioned in the opening comment is required after all.

**Comment by edjeavons** [comment]
I'm still not sure whether this should have been done in Nebula itself (where it can be easily removed by anyone who doesn't like it) or here in Orbit (where opinionated code actually belongs).

Please reopen this issue if you feel it should be moved.
